import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { IoEarthOutline, IoHeartOutline } from 'react-icons/io5';
import { CarouselCustom } from '../src/components/Carousel/Carousel';
import { data, data2, data3 } from '../public/data';

import 'primereact/resources/themes/lara-light-indigo/theme.css'; //theme
import 'primereact/resources/primereact.min.css'; //core css
import 'primeicons/primeicons.css'; //icons
import React, { useState } from 'react';
import { Dialog } from 'primereact/dialog';
import Image from 'next/image';

const Home: NextPage = () => {
  const [showModal, setShowModal] = useState<boolean>(false);
  const [itemSelect, setItemSelect] = useState<any>({});

  const onClick = (item: any) => {
    console.log(item);
    setItemSelect(item);
    setShowModal(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nuestra Historia <IoEarthOutline /> <IoHeartOutline />
        </h1>
        <CarouselCustom
          items={data}
          header='Primer Año'
          onClick={(e) => onClick(e)}
        />
        <CarouselCustom
          items={data2}
          header='Segundo Año'
          onClick={(e) => onClick(e)}
        />
        <CarouselCustom
          items={data3}
          header='Tercer Año'
          onClick={(e) => onClick(e)}
        />
        <Dialog
          onHide={() => setShowModal(false)}
          closeOnEscape
          dismissableMask
          showHeader={false}
          visible={showModal}
        >
          <div
            style={{
              width: '520px',
              height: '900px',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
            }}
          >
            {itemSelect.type === 'img' ? (
              <Image width='300px' height='600px' src={itemSelect.file} />
            ) : (
              <div>
                <video width='500px' height='500px' autoPlay loop controls>
                  <source src={itemSelect.file} type='video/mp4'></source>
                </video>
              </div>
            )}

            <div className={styles.header}>
              <h3 className={styles.subtitle}>{itemSelect.title}</h3>
              <p>{itemSelect.date}</p>
            </div>
            <p className={styles.descriptionModal}>{itemSelect.description}</p>
          </div>
        </Dialog>
      </main>

      <footer className={styles.footer}>Since 02/10/19</footer>
    </div>
  );
};

export default Home;
